[WIP] Modernization/updating c++ pass 1
sierrafoxtrot/srecord pull request #43
Opened 2023-01-27 08:16 UTC by SeanAlling-DojoFive

First pass addressing Issue #41

2023-01-28 23:02 UTC, sierrafoxtrot commented
Thanks @SeanAlling-DojoFive, this is looking great. I'm hoping to get through the review today. 

If there are no questions/issues, are you happy if I squash-merge? I'm still getting the lay of the land on what is considered good form on GH for merging contributions and to me this one looks like a hefty but single update if that makes sense.

2023-01-29 01:32 UTC, SeanAlling-DojoFive commented
That is fine, I am still looking at some cleanup and verifying this are all correct.

Should have my changes done this weekend and then I’ll do a squash merge.
On Jan 28, 2023 at 15:03 -0800, Scott Finneran ***@***.***>, wrote:
> Thanks @SeanAlling-DojoFive, this is looking great. I'm hoping to get through the review today.
> If there are no questions/issues, are you happy if I squash-merge? I'm still getting the lay of the land on what is considered good form on GH for merging contributions and to me this one looks like a hefty but single update if that makes sense.
> —
> Reply to this email directly, view it on GitHub, or unsubscribe.
> You are receiving this because you were mentioned.Message ID: ***@***.***>

2023-01-29 03:56 UTC, sierrafoxtrot commented
No worries, take your time. I'll kick off when you think it's ready.

2023-02-02 08:09 UTC, SeanAlling-DojoFive commented
Okay, I have gone through every file and attempted to move all default member functions to be in class. @sierrafoxtrot I think now is a good time to start taking a look. 

My ultimate goal of this first PR is to address update all constructors. Other PR's will focus on other C++11 modernization's.

2023-02-03 21:49 UTC, sierrafoxtrot commented
@SeanAlling-DojoFive , it's might be worth noting that I need to manually approve the running of the checks which is no doubt a pain (I can relax this setting but not for recently created GH accounts :-( ). We likely have a timezone difference which is slowing things down for you. If you submit a separate smaller commit, GH will no longer consider you a first-time-committer and the checks should trigger automatically speeding up the cycle.

2023-02-08 20:45 UTC, sierrafoxtrot commented
Hey @SeanAlling-DojoFive , I'm getting through this a bit each day. Confident that I'll have it wrapped on the weekend.

2023-02-11 05:44 UTC, sierrafoxtrot requested changes
Thank you Sean for this extensive contribution. My apologies for the time taken to respond but I wanted to do it justice. A couple of minor comments.

2023-02-11 05:44 UTC, sierrafoxtrot commented on srecord/memory/walker/alignment.h
>      unsigned multiple;
Suggest adding a default member init value for completeness

2023-02-13 08:18 UTC, sierrafoxtrot approved these changes

2023-02-13 08:26 UTC, merged